### ISSUE TITLE
Deoplete throws error between two strings

### ISSUE THREAD

**Issue by lriuui0x0** [deoplete-plugins/deoplete-jedi#254]
# Problem summary

Deoplete throws error with two strings

## Expected

Not throwing error

## Environment Information

 * OS: Ubuntu 18.04
 * Neovim version: v0.5.0-dev

## Provide a minimal init.vim with less than 50 lines (required)

```vim
set completeopt=menu,menuone,noselect
set pumheight=20
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('auto_complete_popup', 'manual')
call deoplete#custom#option('min_pattern_length', 0)
inoremap <expr> <C-n> g:deoplete#complete()
call deoplete#custom#option('sources', { 'c': ['clangx'], 'cpp': ['clangx'], 'python': ['jedi', 'buffer'], '_': ['buffer']} )
let clang_options = []
if exists('g:project_include_dir')
    for include_dir in g:project_include_dir
        call add(clang_options, '-I'.include_dir)
    endfor
endif
call deoplete#custom#var('clangx', 'clang_binary', trim(system('which clang')))
call deoplete#custom#var('clangx', 'default_c_options', clang_options)
call deoplete#custom#var('clangx', 'default_cpp_options', clang_options)
let g:deoplete#sources#jedi#show_docstring = 1
```

## Steps to reproduce the issue after starting Neovim (required)

0. Install https://github.com/jiangmiao/auto-pairs (I don't know if there's anything to do with the bug).
1. `nvim main.py`
2. insert `'a''b'`, no space between two strings.
3. put cursor in between two strings.
4. insert space, see the following error:
```
[deoplete] Traceback (most recent call last):                                                                                                                                                              
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 194, in _gather_results
    result = self._get_result(context, source)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 254, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 189, in gather_candidates
    completions = self.get_completions(script)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 137, in get_completions
    return script.completions()
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 214, in completions
    return self.complete(*self._pos, fuzzy=fuzzy)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/helpers.py", line 456, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 202, in complete
    return self._complete(line, column, **kwargs)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 210, in _complete
    return completion.complete()
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 125, in complete
    string, start_leaf, quote = _extract_string_while_in_string(leaf, self._original_position)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 546, in _extract_string_while_in_string
    return return_part_of_leaf(leaf)
  File "/home/lriuui0x0/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 537, in return_part_of_leaf
    start = match.group(0)
AttributeError: 'NoneType' object has no attribute 'group'
Error from jedi: 'NoneType' object has no attribute 'group'.  Use :messages / see above for error details.
```

## Screen shot (if possible)

![Screenshot from 2020-03-22 18-45-57](https://user-images.githubusercontent.com/33423526/77257642-8eb9d580-6c6d-11ea-8822-ac7ea7899457.png)

**Comment by Shougo** [comment]
I have update jedi to the latest.
https://github.com/deoplete-plugins/deoplete-jedi/pull/255

Please use the latest deoplete-jedi.
I think it is fixed on the latest.

**Comment by lriuui0x0** [comment]
@Shougo Unfortunately the problem persists after I updated it to the latest.

**Comment by Shougo** [comment]
OK.   I get it.

But please provide the real minimal vimrc.

It is the real minimal vimrc.

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/src/deoplete-jedi

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#show_docstring = 1

call deoplete#custom#option('auto_complete_popup', 'manual')
call deoplete#custom#option('min_pattern_length', 0)
```

**Comment by Shougo** [comment]
This is jedi's issue.
Please create the new issue in jedi issues.
https://github.com/davidhalter/jedi/issues

And I have found the reason.
The patch fixes the problem for me.

```diff
diff --git a/jedi/api/completion.py b/jedi/api/completion.py
index f8853cdf..c8a2d0c4 100644
--- a/jedi/api/completion.py
+++ b/jedi/api/completion.py
@@ -534,6 +534,8 @@ def _extract_string_while_in_string(leaf, position):
         if leaf.line == position[0]:
             kwargs['endpos'] = position[1] - leaf.column
         match = _string_start.match(leaf.value, **kwargs)
+        if not match:
+            return None, None, None
         start = match.group(0)
         if leaf.line == position[0] and position[1] < leaf.column + match.end():
             return None, None, None
```

**Comment by davidhalter** [comment]
Reproduction:
```
>>> import jedi
>>> jedi.Script("'a' 'b'").complete(column=4)
```

**Comment by Shougo** [comment]
Fixed in the latest version.
